import "./globals.css";

export const metadata = {
  title: "Show 9-day Weather",
  description: "Generated by 香港九日天氣預報",
};

export default function RootLayout({ children }) {
  return (
    <html lang="zh-HK">
      <body className="bg-gray-50">
        <div className="max-w-4xl mx-auto p-4">
          <h1 className="text-3xl font-bold text-center mb-6">
            Show 9-day Weather
          </h1>
          {children}
        </div>
      </body>
    </html>
  );
}
